name: firebase_template
description: Template for Firebase projects
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.5.0
  bloc: ^8.1.2
  build_runner: ^2.4.5
  cloud_firestore: ^4.8.2
  connectivity_plus: ^4.0.1
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  fpdart: ^0.6.0
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  google_sign_in: ^6.1.4
  injectable: ^2.1.2
  intl: ^0.18.0
  rxdart: ^0.27.7
  uuid: ^3.0.7

dev_dependencies:
  auto_route_generator: ^7.1.1
  bloc_test: ^9.1.2
  flutter_gen_runner: ^5.3.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  injectable_generator: ^2.1.6
  json_annotation: ^4.8.1
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true
