// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdVwW-8KQ_3fql7fa1ELTdO7Yble-qaOc',
    appId: '1:944958715633:web:6552a68b8eb59ddd28db50',
    messagingSenderId: '944958715633',
    projectId: 'firebase-template-1010',
    authDomain: 'fir-template-1010.firebaseapp.com',
    storageBucket: 'firebase-template-1010.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChlL66aHT5b781EYrRdWkqXBmDYmPjVQQ',
    appId: '1:944958715633:android:161fefd6c2c77bd628db50',
    messagingSenderId: '944958715633',
    projectId: 'firebase-template-1010',
    storageBucket: 'firebase-template-1010.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMGCKsJ2hPsDQUgke8EXleQtz7ZCEjqkA',
    appId: '1:944958715633:ios:8fb9c5b521aa15ae28db50',
    messagingSenderId: '944958715633',
    projectId: 'firebase-template-1010',
    storageBucket: 'firebase-template-1010.appspot.com',
    iosClientId: '944958715633-af494ffd9o5mlau1ml58gp3cgn5simh7.apps.googleusercontent.com',
    iosBundleId: 'com.example.verygoodcore.firebase-template',
  );
}
